import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useUser } from "@clerk/clerk-react";
import {
  FaCalendarAlt,
  FaClock,
  FaUser,
  FaCheck,
  FaTimes,
  FaRobot,
  FaHeartbeat,
  FaPills,
} from "react-icons/fa";
import { Link, Navigate } from "react-router-dom";
import { Separator } from "@/components/ui/separator";
import { useEffect, useState } from "react";

function MedicationCard(props) {
  const [treatmentData, setTreatmentData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const statusData = [
    {
      status: "No Depression",
      severity: "normal",
      aiConfidence: "95%",
      lastAssessment: "Today",
    },
  ];

  const session = {
    date: "05/04/2024", // MM/DD/YYYY
    time: "09:00 PM", // 12-hour format
  };

  // Fetch treatment data from database based on depression type
  useEffect(() => {
    const fetchTreatmentData = async () => {
      try {
        setLoading(true);

        const depressionType = props.status || "No Depression";

        // Replace with your actual API endpoint
        const response = await fetch(
          `http://localhost:8000/treatments/${encodeURIComponent(
            depressionType
          )}`,
          {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
            },
          }
        );

        if (!response.ok) {
          throw new Error("Failed to fetch treatment data");
        }

        const data = await response.json();
        setTreatmentData(data);
      } catch (err) {
        setError(err.message);
        console.error("Error fetching treatment data:", err);
      } finally {
        setLoading(false);
      }
    };

    // Only fetch if we have a status
    if (props.status) {
      fetchTreatmentData();
    }
  }, [props.status]);

  const getStatusColor = (statu) => {
    const statusLower = statu?.toLowerCase();
    if (statusLower.includes("no depression")) {
      return "text-green-600 bg-green-50 border-green-200";
    } else if (statusLower.includes("mild")) {
      return "text-yellow-600 bg-yellow-50 border-yellow-200";
    } else if (statusLower.includes("moderate")) {
      return "text-orange-600 bg-orange-50 border-orange-200";
    } else if (statusLower.includes("severe")) {
      return "text-red-600 bg-red-50 border-red-200";
    }
    return "text-blue-600 bg-blue-50 border-blue-200";
  };

  const { isLoaded, isSignedIn, user } = useUser();

  if (!isLoaded || loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="flex flex-col items-center space-y-4">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
          <p className="text-gray-600">Loading treatment plan...</p>
        </div>
      </div>
    );
  }

  if (!isSignedIn) {
    return <Navigate to="/sign-in" />;
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="flex flex-col items-center space-y-4">
          <div className="text-red-600 text-6xl">⚠️</div>
          <p className="text-red-600 text-lg font-semibold">
            Error loading treatment plan
          </p>
          <p className="text-gray-600">{error}</p>
          <Button
            onClick={() => window.location.reload()}
            className="bg-blue-600 hover:bg-blue-700"
          >
            Try Again
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header Section */}
      <div className="bg-white shadow-sm border-b">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center space-x-4">
            <div className="p-3 bg-blue-100 rounded-full">
              <FaPills className="text-blue-600 text-xl" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">
                Treatment & Medication Plan
              </h1>
              <p className="text-gray-600">
                Personalized care plan generated by UniMind AI
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {statusData.map((statusItem, index) => (
          <Card key={index} className="shadow-lg border-0 bg-white">
            <CardHeader className="bg-gradient-to-r from-blue-50 to-green-50 border-b">
              <div className="flex items-center justify-between">
                <CardTitle className="text-xl font-semibold text-gray-800 flex items-center space-x-2">
                  <FaHeartbeat className="text-green-600" />
                  <span>Current Status: {props.status}</span>
                </CardTitle>
                <div className="flex items-center space-x-4">
                  <div className="text-sm text-gray-600">
                    <span className="font-medium">AI Confidence:</span>{" "}
                    {statusItem.aiConfidence}
                  </div>
                  <div
                    className={`px-3 py-1 bg-green-100 rounded-full text-sm font-medium ${getStatusColor(
                      props.status
                    )}`}
                  >
                    {statusItem.severity}
                  </div>
                </div>
              </div>
            </CardHeader>

            <CardContent className="p-6 space-y-6">
              {/* AI Analysis Header */}
              <div className="flex items-center space-x-3 p-4 bg-blue-50 rounded-lg border-l-4 border-blue-400">
                <div className="p-2 bg-blue-100 rounded-full">
                  <FaRobot className="text-blue-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-blue-900">
                    UniMind AI Analysis
                  </h3>
                  <p className="text-sm text-blue-700">
                    Generated personalized treatment plan
                  </p>
                </div>
              </div>

              {/* Session Information */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="flex items-center space-x-3 p-3 bg-gray-50 rounded-lg">
                  <div className="p-2 bg-green-100 rounded-full">
                    <FaCalendarAlt className="text-green-600" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-600">
                      Assessment Date
                    </p>
                    <Input
                      type="text"
                      value={session.date}
                      readOnly
                      className="border-0 bg-transparent p-0 text-gray-800 font-semibold focus:ring-0"
                    />
                  </div>
                </div>

                <div className="flex items-center space-x-3 p-3 bg-gray-50 rounded-lg">
                  <div className="p-2 bg-purple-100 rounded-full">
                    <FaClock className="text-purple-600" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-600">Time</p>
                    <Input
                      type="text"
                      value={session.time}
                      readOnly
                      className="border-0 bg-transparent p-0 text-gray-800 font-semibold focus:ring-0"
                    />
                  </div>
                </div>

                <div className="flex items-center space-x-3 p-3 bg-gray-50 rounded-lg">
                  <div className="p-2 bg-blue-100 rounded-full">
                    <FaUser className="text-blue-600" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-gray-600">Patient</p>
                    <p className="text-gray-800 font-semibold">
                      {user.fullName}
                    </p>
                  </div>
                </div>
              </div>

              <Separator />

              {/* Recommendations Section */}
              <div className="space-y-4">
                <div className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-green-500 rounded-full"></div>
                  <h3 className="text-lg font-semibold text-gray-800">
                    Lifestyle Recommendations
                  </h3>
                </div>
                <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                  {treatmentData?.lifestyle &&
                  treatmentData.lifestyle.length > 0 ? (
                    <ul className="space-y-2">
                      {treatmentData.lifestyle.map((rec, idx) => (
                        <li key={idx} className="flex items-start space-x-2">
                          <FaCheck className="text-green-600 mt-1 flex-shrink-0" />
                          <span className="text-gray-700">{rec}</span>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-gray-500 italic">
                      No lifestyle recommendations available.
                    </p>
                  )}
                </div>
              </div>

              <Separator />

              {/* Treatments Section */}
              <div className="space-y-4">
                <div className="flex items-center space-x-2">
                  <div className="w-4 h-4 bg-blue-500 rounded-full"></div>
                  <h3 className="text-lg font-semibold text-gray-800">
                    Recommended Treatments
                  </h3>
                </div>
                <div className="bg-blue-50 rounded-lg p-4 border border-blue-200">
                  {treatmentData?.treatments &&
                  treatmentData.treatments.length > 0 ? (
                    <ul className="space-y-2">
                      {treatmentData.treatments.map((treatment, idx) => (
                        <li key={idx} className="flex items-start space-x-2">
                          <FaHeartbeat className="text-blue-600 mt-1 flex-shrink-0" />
                          <span className="text-gray-700">{treatment}</span>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-gray-500 italic">
                      No treatments available.
                    </p>
                  )}
                </div>
              </div>

              {/* Important Note */}
              <div className="bg-yellow-50 rounded-lg p-4 border border-yellow-200">
                <div className="flex items-start space-x-3">
                  <div className="p-1 bg-yellow-100 rounded-full">
                    <svg
                      className="w-4 h-4 text-yellow-600"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path
                        fillRule="evenodd"
                        d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-yellow-800">
                      Important Notice
                    </p>
                    <p className="text-sm text-yellow-700 mt-1">
                      This treatment plan is generated by AI and should be
                      reviewed with a qualified healthcare professional before
                      implementation.
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>

            <CardFooter className="bg-gray-50 border-t p-6">
              <div className="flex flex-col sm:flex-row gap-4 w-full">
                <Button
                  asChild
                  className="flex-1 bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 text-white font-medium py-3 rounded-lg transition-all duration-200 shadow-md hover:shadow-lg"
                >
                  <Link
                    to="/dashboard/accept-treatment"
                    className="flex items-center justify-center space-x-2"
                  >
                    <FaCheck className="text-sm" />
                    <span>Accept Treatment Plan</span>
                  </Link>
                </Button>

                <Button
                  asChild
                  className="flex-1 bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 text-white font-medium py-3 rounded-lg transition-all duration-200 shadow-md hover:shadow-lg"
                >
                  <Link
                    to="/dashboard/decline-treatment"
                    className="flex items-center justify-center space-x-2"
                  >
                    <FaTimes className="text-sm" />
                    <span>Request Consultation</span>
                  </Link>
                </Button>
              </div>
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
}

export default MedicationCard;
